const MENU = [
    // Салаты
    { id: 1, category: "salads", name: "Яблочный", price: "45000", image: "/images/menu/1.png" },
    { id: 2, category: "salads", name: "Французский", price: "45000", image: "/images/menu/2.png" },
    { id: 3, category: "salads", name: "Император", price: "55000", image: "/images/menu/3.png" },
    { id: 4, category: "salads", name: "Мимоза", price: "45000", image: "/images/menu/4.png" },
    { id: 5, category: "salads", name: "Дубок", price: "50000", image: "/images/menu/5.png" },
    { id: 6, category: "salads", name: "Сельд под шубой", price: "50000", image: "/images/menu/6.png" },
    { id: 7, category: "salads", name: "Парвина", price: "55000", image: "/images/menu/7.png" },
    { id: 8, category: "salads", name: "Мужской каприз", price: "50000", image: "/images/menu/8.png" },
    { id: 9, category: "salads", name: "Цезарь", price: "50000", image: "/images/menu/9.png" },
    { id: 10, category: "salads", name: "Шейх", price: "50000", image: "/images/menu/10.png" },
    { id: 11, category: "salads", name: "Оливье", price: "45000", image: "/images/menu/11.png" },
    { id: 12, category: "salads", name: "Сердце", price: "45000", image: "/images/menu/12.png" },
    { id: 13, category: "salads", name: "Салат от шефа", price: "85000", image: "/images/menu/13.png" },
    { id: 14, category: "salads", name: "Бурато", price: "85000", image: "/images/menu/14.png" },
    { id: 15, category: "salads", name: "Капрезе", price: "65000", image: "/images/menu/15.png" },
    { id: 16, category: "salads", name: "Ростбиф", price: "85000", image: "/images/menu/16.png" },
    { id: 17, category: "salads", name: "Греческий", price: "50000", image: "/images/menu/17.png" },
    { id: 18, category: "salads", name: "Будур", price: "55000", image: "/images/menu/18.png" },
    { id: 19, category: "salads", name: "Японский", price: "55000", image: "/images/menu/19.png" },
    { id: 20, category: "salads", name: "Язык", price: "50000", image: "/images/menu/20.png" },
    { id: 21, category: "salads", name: "витаминка", price: "45000", image: "/images/menu/21.png" },
    { id: 22, category: "salads", name: "Салат с руколой", price: "65000", image: "/images/menu/22.png" },
    { id: 23, category: "salads", name: "Язычок", price: "50000", image: "/images/menu/23.png" },
    { id: 24, category: "salads", name: "Теплый с руколой", price: "70000", image: "/images/menu/24.png" },
    { id: 25, category: "salads", name: "Баклажановое ассорти", price: "60000", image: "/images/menu/25.png" },
    { id: 26, category: "salads", name: "Баклажановые рулетики", price: "35000", image: "/images/menu/26.png" },
    { id: 27, category: "salads", name: "Баклажаны в соусе", price: "35000", image: "/images/menu/27.png" },
    { id: 28, category: "salads", name: "Ачик-чучук", price: "40000", image: "/images/menu/28.png" },
    { id: 29, category: "salads", name: "Свежий", price: "35000", image: "/images/menu/29.png" },
    { id: 30, category: "salads", name: "Грибной", price: "45000", image: "/images/menu/30.png" },
    { id: 31, category: "salads", name: "Чакка с редькой", price: "20000", image: "/images/menu/31.png" },
    { id: 32, category: "salads", name: "Овозная нарезка", price: "40000", image: "/images/menu/32.png" },
    { id: 33, category: "salads", name: "Чакка", price: "20000", image: "/images/menu/33.png" },

    // Холодные закуски
    { id: 34, category: "cold_wishes", name: "Маринованое ассорти", price: "55000", image: "/images/menu/34.png" },
    { id: 35, category: "cold_wishes", name: "Фирменое ассорти", price: "60000", image: "/images/menu/35.png" },
    { id: 36, category: "cold_wishes", name: "Сельд с картошкой", price: "50000", image: "/images/menu/36.png" },
    { id: 37, category: "cold_wishes", name: "Рыбное ассорти", price: "190000", image: "/images/menu/37.png" },
    { id: 38, category: "cold_wishes", name: "Мясное ассорти (маленькое)", price: "180000", image: "/images/menu/38.png" },
    { id: 39, category: "cold_wishes", name: "Мясное ассорти (большое)", price: "210000", image: "/images/menu/38.png" },

    // Ассорти
    { id: 40, category: "assorted", name: "Сырная тарелка", price: "160000", image: "/images/menu/40.png" },
    { id: 41, category: "assorted", name: "Овощной букет", price: "65000", image: "/images/menu/41.png" },
    { id: 42, category: "assorted", name: "Фруктовое ассорти", price: "130000-180000", image: "/images/menu/42.png" },

    // Супы
    { id: 43, category: "soups", name: "Куза шурпа", price: "40000", image: "/images/menu/43.png" },
    { id: 44, category: "soups", name: "Солянка", price: "30000", image: "/images/menu/44.png" },
    { id: 45, category: "soups", name: "Пельмени", price: "35000", image: "/images/menu/45.png" },
    { id: 46, category: "soups", name: "Суп с фрикадельками", price: "30000", image: "/images/menu/46.png" },
    { id: 47, category: "soups", name: "Хом шурпа", price: "35000", image: "/images/menu/47.png" },
    { id: 48, category: "soups", name: "Балаза шурпа", price: "35000", image: "/images/menu/48.png" },

    // Вторые блюда
    { id: 49, category: "second_wishes", name: "Крылышки", price: "85000", image: "/images/menu/49.png" },
    { id: 50, category: "second_wishes", name: "Чахохбили курица", price: "90000", image: "/images/menu/50.png" },
    { id: 51, category: "second_wishes", name: "Табака под прессом", price: "75000", image: "/images/menu/51.png" },
    { id: 52, category: "second_wishes", name: "КФС Филе", price: "85000", image: "/images/menu/52.png" },
    { id: 53, category: "second_wishes", name: "КФС с косточкой", price: "75000", image: "/images/menu/53.png" },
    { id: 54, category: "second_wishes", name: "Куриный жиз с овощами", price: "80000", image: "/images/menu/54.png" },
    { id: 55, category: "second_wishes", name: "Вагурри ширбоз баранина", price: "270000", image: "/images/menu/55.png" },
    { id: 56, category: "second_wishes", name: "Вагурри корейка баранина", price: "280000", image: "/images/menu/56.png" },
    { id: 57, category: "second_wishes", name: "Тандыр баранина", price: "260000", image: "/images/menu/57.png" },
    { id: 58, category: "second_wishes", name: "Мясо тушеное", price: "240000", image: "/images/menu/58.png" },
    { id: 59, category: "second_wishes", name: "Говяжьи ребра", price: "240000", image: "/images/menu/59.png" },
    { id: 60, category: "second_wishes", name: "Баранина на мангале", price: "280000", image: "/images/menu/60.png" },
    { id: 61, category: "second_wishes", name: "Бон филе", price: "300000", image: "/images/menu/61.png" },
    { id: 62, category: "second_wishes", name: "Жиз уйгурский говядина", price: "250000", image: "/images/menu/62.png" },
    { id: 63, category: "second_wishes", name: "Жиз уйгурский с овощами", price: "250000", image: "/images/menu/63.png" },
    { id: 64, category: "second_wishes", name: "Люля кебаб", price: "50000", image: "/images/menu/64.png" },
    { id: 65, category: "second_wishes", name: "Школьная котлета", price: "20000", image: "/images/menu/65.png" },
    { id: 66, category: "second_wishes", name: "Манты", price: "10000", image: "/images/menu/66.png" },
    { id: 67, category: "second_wishes", name: "Голень баранина", price: "240000", image: "/images/menu/67.png" },
    { id: 68, category: "second_wishes", name: "Казан кебаб", price: "55000", image: "/images/menu/68.png" },
    { id: 69, category: "second_wishes", name: "Поджарка", price: "50000", image: "/images/menu/69.png" },
    { id: 70, category: "second_wishes", name: "Бризоль говядина", price: "85000", image: "/images/menu/70.png" },
    { id: 71, category: "second_wishes", name: "Блюда от шефа", price: "85000", image: "/images/menu/71.png" },
    { id: 72, category: "second_wishes", name: "Отбивная", price: "85000", image: "/images/menu/72.png" },
    { id: 73, category: "second_wishes", name: "Бифстроганов", price: "85000", image: "/images/menu/73.png" },
    { id: 74, category: "second_wishes", name: "Язык в грибном соусе", price: "100000", image: "/images/menu/74.png" },
    { id: 75, category: "second_wishes", name: "Бон-филе под сыром", price: "300000", image: "/images/menu/75.png" },
    { id: 76, category: "second_wishes", name: "Жареная печень", price: "120000", image: "/images/menu/76.png" },
    { id: 77, category: "second_wishes", name: "Куртоба", price: "45000", image: "/images/menu/77.png" },
    { id: 78, category: "second_wishes", name: "Каиш", price: "50000-75000", image: "/images/menu/78.png" },
    { id: 79, category: "second_wishes", name: "Олот сомса", price: "12000", image: "/images/menu/79.png" },
    { id: 80, category: "second_wishes", name: "Бешбармак", price: "85000", image: "/images/menu/80.png" },

    // Шашлыки
    { id: 81, category: "second_wishes", name: "Семечка баранина", price: "37500", image: "/images/menu/81.png" },
    { id: 82, category: "second_wishes", name: "Ковурга баранина", price: "37500", image: "/images/menu/82.png" },
    { id: 83, category: "second_wishes", name: "Думба", price: "32500", image: "/images/menu/83.png" },
    { id: 84, category: "shashlik", name: "Филе говядина", price: "37500", image: "/images/menu/84.png" },
    { id: 85, category: "shashlik", name: "Кусковой говядина", price: "32500", image: "/images/menu/85.png" },
    { id: 86, category: "shashlik", name: "Молотый говядина", price: "22500", image: "/images/menu/86.png" },
    { id: 87, category: "shashlik", name: "Болгарский перец", price: "20000", image: "/images/menu/87.png" },
    { id: 88, category: "shashlik", name: "Помидор", price: "18000", image: "/images/menu/88.png" },
    { id: 89, category: "shashlik", name: "Ковказский", price: "45000", image: "/images/menu/89.png" },
    { id: 90, category: "shashlik", name: "Рыбный шашлык", price: "34000", image: "/images/menu/90.png" },
    { id: 91, category: "shashlik", name: "Крышылки", price: "20000", image: "/images/menu/91.png" },
    { id: 92, category: "shashlik", name: "Печень", price: "20000", image: "/images/menu/92.png" },

    // Мясной сет
    { id: 93, category: "meat_set", name: "Мясной сет-1", price: "600000", image: "/images/menu/93.png" },
    { id: 94, category: "meat_set", name: "Мясной сет-2", price: "700000", image: "/images/menu/94.png" },
    { id: 95, category: "meat_set", name: "Мясной сет-3", price: "800000", image: "/images/menu/95.png" },
    { id: 96, category: "meat_set", name: "Куриный жиз", price: "40000", image: "/images/menu/96.png" },
    { id: 97, category: "meat_set", name: "Люля кебаб", price: "40000", image: "/images/menu/97.png" },
    { id: 98, category: "meat_set", name: "Тушеное мясо", price: "40000", image: "/images/menu/98.png" },
    { id: 99, category: "meat_set", name: "Лангет", price: "40000", image: "/images/menu/99.png" },
];

export default MENU;